name: Build Control Programs

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  discussions: write

jobs:
  build-linux:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          # - aarch64-unknown-linux-musl
          - riscv64gc-unknown-linux-gnu
          # - riscv64gc-unknown-linux-musl

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v2
        with:
          cache-targets: true

      - name: Install Build Requirements
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pkg-config
          sudo apt-get install libudev-dev

          sudo apt-get install -y \
            gcc-riscv64-linux-gnu g++-riscv64-linux-gnu libc6-dev-riscv64-cross \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross \
            musl \
            pkgconf

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Install cross (if needed)
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build with cross
        run: |
          cd Program
          if [[ "${{ matrix.target }}" == "riscv64gc-unknown-linux-musl" ]]; then
            export PKG_CONFIG_SYSROOT_DIR=/usr/riscv64-linux-gnu
            export PKG_CONFIG_PATH=/usr/riscv64-linux-gnu/lib/pkgconfig:/usr/riscv64-linux-gnu/share/pkgconfig
          elif [[ "${{ matrix.target }}" == "riscv64gc-unknown-linux-gnu" ]]; then
            export PKG_CONFIG_SYSROOT_DIR=/usr/riscv64-linux-gnu
            export PKG_CONFIG_PATH=/usr/riscv64-linux-gnu/lib/pkgconfig:/usr/riscv64-linux-gnu/share/pkgconfig
          elif [[ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]]; then
            export PKG_CONFIG_SYSROOT_DIR=/usr/aarch64-linux-gnu
            export PKG_CONFIG_PATH=/usr/aarch64-linux-gnu/lib/pkgconfig:/usr/aarch64-linux-gnu/share/pkgconfig
          elif [[ "${{ matrix.target }}" == "aarch64-unknown-linux-musl" ]]; then
            export PKG_CONFIG_SYSROOT_DIR=/usr/aarch64-linux-gnu
            export PKG_CONFIG_PATH=/usr/aarch64-linux-gnu/lib/pkgconfig:/usr/aarch64-linux-gnu/share/pkgconfig
          fi
          RUST_BACKTRACE=1 cross build --release --target ${{ matrix.target }}

      - name: Prepare artifact
        run: |
          mkdir -p artifacts
          BIN_PATH="Program/target/${{ matrix.target }}/release/tf_mux"
          if [[ -f "${BIN_PATH}.exe" ]]; then
            cp "${BIN_PATH}.exe" "artifacts/tf_mux-${{ matrix.target }}.exe"
          else
            cp "${BIN_PATH}" "artifacts/tf_mux-${{ matrix.target }}"
          fi

      - name: Upload artifact to Actions Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tf_mux_ctrl-${{ matrix.target }}
          path: artifacts/*

      - name: Upload artifact to GitHub Release (if tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    name: Build for ${{ matrix.target }}
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - aarch64-pc-windows-msvc

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v2
        with:
          cache-targets: true

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Install cross (if needed)
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build with cross
        run: |
          cd Program
          cargo build --release --target ${{ matrix.target }}

      - name: Prepare artifact
        run: |
          New-Item -ItemType Directory -Force -Path artifacts
          if (Test-Path "Program/target/${{ matrix.target }}/release/tf_mux.exe") {
            Copy-Item "Program/target/${{ matrix.target }}/release/tf_mux.exe" -Destination "artifacts/$env:BIN_NAME-${{ matrix.target }}.exe"
          } elseif (Test-Path "Program/target/${{ matrix.target }}/release/tf_mux") {
            Copy-Item "Program/target/${{ matrix.target }}/release/tf_mux" -Destination "artifacts/$env:BIN_NAME-${{ matrix.target }}"
          } else {
            Write-Host "Binary not found!"
            exit 1
          }

      - name: Upload artifact to Actions Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tf_mux_ctrl-${{ matrix.target }}
          path: artifacts/*

      - name: Upload artifact to GitHub Release (if tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    name: Build for ${{ matrix.target }}
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-apple-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v2
        with:
          cache-targets: true

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Install cross (if needed)
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build with cross
        run: |
          cd Program
          cargo build --release --target ${{ matrix.target }}

      - name: Prepare artifact
        run: |
          mkdir -p artifacts
          BIN_PATH="Program/target/${{ matrix.target }}/release/tf_mux"
          if [[ -f "${BIN_PATH}.exe" ]]; then
            cp "${BIN_PATH}.exe" "artifacts/tf_mux-${{ matrix.target }}.exe"
          else
            cp "${BIN_PATH}" "artifacts/tf_mux-${{ matrix.target }}"
          fi

      - name: Upload artifact to Actions Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tf_mux_ctrl-${{ matrix.target }}
          path: artifacts/*

      - name: Upload artifact to GitHub Release (if tag)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}